# Generated by Django 3.0.7 on 2021-06-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210609_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='instagram_link',
            new_name='google_plus_link',
        ),
    ]
